# **Q4. Eigenfaces - Face classification using PCA (40 classes)**
a) Use the following "face.csv" file to classify the faces of 40 different people.

 b) Do not use in-built function for implementing PCA.

 c) Use appropriate classifier taught in class (any classification algorithm taught in class like Bayes classifier, minimum distance clasifier, and so on)

d) Refer to the following link for a description of the dataset


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [17]:
df = pd.read_csv('face.csv')
df

0         1         2         3         4         5         6  \
0    0.309917  0.367769  0.417355  0.442149  0.528926  0.607438  0.657025   
1    0.454545  0.471074  0.512397  0.557851  0.595041  0.640496  0.681818   
2    0.318182  0.400826  0.491736  0.528926  0.586777  0.657025  0.681818   
3    0.198347  0.194215  0.194215  0.194215  0.190083  0.190083  0.243802   
4    0.500000  0.545455  0.582645  0.623967  0.648760  0.690083  0.694215   
..        ...       ...       ...       ...       ...       ...       ...   
395  0.400826  0.495868  0.570248  0.632231  0.648760  0.640496  0.661157   
396  0.367769  0.367769  0.351240  0.301653  0.247934  0.247934  0.367769   
397  0.500000  0.533058  0.607438  0.628099  0.657025  0.632231  0.657025   
398  0.214876  0.219008  0.219008  0.223140  0.210744  0.202479  0.276859   
399  0.516529  0.462810  0.280992  0.252066  0.247934  0.367769  0.574380   

            7         8         9  ...      4087      4088      4089  \
0    0.677686  0.690083  0.685950  ...  0.669422  0.652893  0.661157   
1    0.702479  0.710744  0.702479  ...  0.157025  0.136364  0.148760   
2    0.685950  0.702479  0.698347  ...  0.132231  0.181818  0.136364   
3    0.404959  0.483471  0.516529  ...  0.636364  0.657025  0.685950   
4    0.714876  0.723140  0.731405  ...  0.161157  0.177686  0.173554   
..        ...       ...       ...  ...       ...       ...       ...   
395  0.636364  0.665289  0.698347  ...  0.396694  0.264463  0.099174   
396  0.512397  0.574380  0.628099  ...  0.334711  0.289256  0.285124   
397  0.669422  0.673554  0.702479  ...  0.148760  0.152893  0.161157   
398  0.400826  0.487603  0.549587  ...  0.392562  0.367769  0.409091   
399  0.615702  0.661157  0.615702  ...  0.264463  0.293388  0.301653   

         4090      4091      4092      4093      4094      4095  target  
0    0.475207  0.132231  0.148760  0.152893  0.161157  0.157025       0  
1    0.152893  0.152893  0.152893  0.152893  0.152893  0.152893       0  
2    0.128099  0.148760  0.144628  0.140496  0.148760  0.152893       0  
3    0.727273  0.743802  0.764463  0.752066  0.752066  0.739669       0  
4    0.177686  0.177686  0.177686  0.177686  0.173554  0.173554       0  
..        ...       ...       ...       ...       ...       ...     ...  
395  0.181818  0.243802  0.247934  0.161157  0.157025  0.136364      39  
396  0.338843  0.404959  0.458678  0.487603  0.512397  0.549587      39  
397  0.161157  0.173554  0.157025  0.177686  0.148760  0.190083      39  
398  0.479339  0.524793  0.545455  0.574380  0.590909  0.603306      39  
399  0.293388  0.322314  0.322314  0.359504  0.355372  0.384298      39  

[400 rows x 4097 columns]

In [20]:
df['target'].nunique()

40

In [21]:
train_data_set = df.iloc[2:10]

for i in range(10, 400, 10):
  train_data_set = train_data_set.append(df.iloc[i + 2:i + 10], ignore_index = True)


In [22]:
test_data_set = df.iloc[0:2]

for i in range(10, 400, 10):
  test_data_set = test_data_set.append(df.iloc[i:i + 2], ignore_index = True)

In [23]:
train_data_set = np.transpose(train_data_set)

test_data_set = np.transpose(test_data_set)

d = 4096

In [24]:
def mean_PCA(train_data_set):
    train_data_set_mean = np.mean(train_data_set, axis = 1)
    return np.array(train_data_set_mean)

In [33]:
train_data_set_mean = mean_PCA(train_data_set)

train_data_set_covariance_matrix = np.cov(train_data_set)

eigen_values, eigen_vectors = np.linalg.eigh(train_data_set_covariance_matrix)

In [36]:
eigen_vectors

array([[ 1.09673762e-10, -1.36248316e-22,  0.00000000e+00, ...,
         2.58987596e-02, -1.11002420e-02, -2.89133830e-03],
       [ 6.34011868e-01,  1.68234998e-03, -1.57611540e-02, ...,
         3.20490500e-02, -1.03632898e-02, -3.43233021e-03],
       [ 5.16062564e-01, -3.92703309e-02, -3.44897115e-03, ...,
         3.76261017e-02, -9.95050378e-03, -3.88651704e-03],
       ...,
       [-5.80040314e-03, -6.73512765e-03, -3.50239346e-02, ...,
        -2.46785462e-02,  1.63410682e-02,  1.64872853e-03],
       [ 7.67892218e-03, -1.15418428e-04,  1.24062167e-02, ...,
        -2.37027265e-02,  1.19902194e-02,  2.36237474e-03],
       [ 1.47328279e-04, -3.40683438e-04, -1.27949039e-03, ...,
         1.15434010e-01,  1.65745797e-01,  9.77319215e-01]])

In [37]:
eigen_pairs = [(np.abs(eigen_values[i]), eigen_vectors[:, i]) for i in range(len(eigen_values))]

eigen_pairs.sort(key = lambda x : x[0], reverse = True)

eigen_pairs

[(139.36162683800723,
  array([-0.00289134, -0.00343233, -0.00388652, ...,  0.00164873,
          0.00236237,  0.97731921])),
 (14.499807603235132,
  array([-0.01110024, -0.01036329, -0.0099505 , ...,  0.01634107,
          0.01199022,  0.1657458 ])),
 (11.501218289351298,
  array([ 0.02589876,  0.03204905,  0.0376261 , ..., -0.02467855,
         -0.02370273,  0.11543401])),
 (6.164191206493249,
  array([-0.00042946,  0.00141395,  0.00214601, ...,  0.01297994,
          0.01022299, -0.00493227])),
 (3.744489448288152,
  array([ 0.0031369 ,  0.00598666,  0.01436208, ..., -0.03232048,
         -0.03100657, -0.01374353])),
 (2.678989204663223,
  array([-0.02981562, -0.02896639, -0.02541967, ..., -0.03341115,
         -0.03217765,  0.01979889])),
 (2.4661057376538924,
  array([ 0.01354091,  0.01418474,  0.01206256, ..., -0.03256521,
         -0.03212349,  0.01607089])),
 (1.7915209761326731,
  array([-0.04476043, -0.03454504, -0.02433952, ..., -0.03187595,
         -0.03331386, -0.01962603

In [11]:
def get_reduced_dimension(eigen_pairs, eigen_values, percent):
    eigen_values_sum = np.sum(eigen_values)
    eigen_values_sum_reduced_dimension = percent * eigen_values_sum / 100
    sum = 0.0
    count = 0
    for i in eigen_pairs:
        if(sum < eigen_values_sum_reduced_dimension):
            sum += i[0]
            count += 1
        else:
            break
    return count

In [13]:
d_prime = get_reduced_dimension(eigen_pairs, eigen_values, 95)
d_prime

111

In [26]:
matrix_w = eigen_pairs[0][1].reshape(d, 1)

In [27]:
for i in range(1, d_prime):
    matrix_w = np.hstack((matrix_w, eigen_pairs[i][1].reshape(d, 1)))

In [28]:
train_data_set_transformed = np.transpose(matrix_w.T.dot(train_data_set))

test_data_set_transformed = np.transpose(matrix_w.T.dot(test_data_set))


In [31]:
train_data_set_transformed

array([[-8.29290331e+00,  3.02285622e+01,  2.41543149e+01, ...,
        -8.73786293e-01, -5.66741831e-02,  4.04960725e-02],
       [-7.64557547e+00,  3.51417325e+01,  1.22750050e+01, ...,
        -4.65948071e-01,  1.30449372e-01,  4.67527665e-01],
       [-8.11817755e+00,  2.82085837e+01,  2.50852021e+01, ...,
        -7.88608451e-01, -1.19643270e-01,  2.59223977e-01],
       ...,
       [ 3.13947253e+01,  3.04409600e+01,  2.56418657e+01, ...,
        -3.19052588e-01, -6.48079946e-02,  3.55924352e-01],
       [ 3.02008171e+01,  4.09947952e+01,  2.00702084e+01, ...,
        -4.68537219e-01, -6.65559262e-02,  6.07810380e-01],
       [ 3.08571030e+01,  3.49733539e+01,  2.34102081e+01, ...,
        -5.84183796e-01, -2.10560625e-01, -7.79441569e-02]])

In [32]:
test_data_set_transformed

array([[-8.44927168e+00,  3.16692396e+01,  2.39182316e+01, ...,
        -3.32461002e-01,  7.65168901e-02,  1.27667589e-01],
       [-7.64817839e+00,  2.41778890e+01,  2.68682159e+01, ...,
        -6.99703674e-01, -4.19659079e-01,  3.49745287e-01],
       [-6.38846022e+00,  2.70653310e+01,  2.20660192e+01, ...,
        -7.52367705e-01, -4.21027474e-02,  4.75540818e-02],
       ...,
       [ 3.20582337e+01,  2.32533442e+01,  2.17620683e+01, ...,
        -4.36503361e-01, -9.39702391e-02,  7.04456699e-01],
       [ 3.11863400e+01,  3.09539340e+01,  2.59429320e+01, ...,
        -5.11462215e-01,  3.35048702e-02,  1.73611141e-01],
       [ 3.03147586e+01,  3.74984528e+01,  2.45753793e+01, ...,
        -4.34260533e-01, -3.09021547e-01,  5.99813400e-01]])

# Bayes Classifier Code

## **Bayes Classifier with dimesion = 4096**

In [53]:
train_data_set

0         1         2         3         4         5         6  \
0    0.318182  0.400826  0.491736  0.528926  0.586777  0.657025  0.681818   
1    0.198347  0.194215  0.194215  0.194215  0.190083  0.190083  0.243802   
2    0.500000  0.545455  0.582645  0.623967  0.648760  0.690083  0.694215   
3    0.549587  0.545455  0.541322  0.537190  0.537190  0.533058  0.528926   
4    0.330578  0.305785  0.330578  0.351240  0.425620  0.500000  0.603306   
..        ...       ...       ...       ...       ...       ...       ...   
315  0.400826  0.495868  0.570248  0.632231  0.648760  0.640496  0.661157   
316  0.367769  0.367769  0.351240  0.301653  0.247934  0.247934  0.367769   
317  0.500000  0.533058  0.607438  0.628099  0.657025  0.632231  0.657025   
318  0.214876  0.219008  0.219008  0.223140  0.210744  0.202479  0.276859   
319  0.516529  0.462810  0.280992  0.252066  0.247934  0.367769  0.574380   

            7         8         9  ...      4086      4087      4088  \
0    0.685950  0.702479  0.698347  ...  0.074380  0.132231  0.181818   
1    0.404959  0.483471  0.516529  ...  0.652893  0.636364  0.657025   
2    0.714876  0.723140  0.731405  ...  0.190083  0.161157  0.177686   
3    0.533058  0.590909  0.611570  ...  0.623967  0.619835  0.623967   
4    0.632231  0.644628  0.644628  ...  0.516529  0.541322  0.541322   
..        ...       ...       ...  ...       ...       ...       ...   
315  0.636364  0.665289  0.698347  ...  0.388430  0.396694  0.264463   
316  0.512397  0.574380  0.628099  ...  0.380165  0.334711  0.289256   
317  0.669422  0.673554  0.702479  ...  0.194215  0.148760  0.152893   
318  0.400826  0.487603  0.549587  ...  0.446281  0.392562  0.367769   
319  0.615702  0.661157  0.615702  ...  0.276859  0.264463  0.293388   

         4089      4090      4091      4092      4093      4094  target  
0    0.136364  0.128099  0.148760  0.144628  0.140496  0.148760     0.0  
1    0.685950  0.727273  0.743802  0.764463  0.752066  0.752066     0.0  
2    0.173554  0.177686  0.177686  0.177686  0.177686  0.173554     0.0  
3    0.615702  0.661157  0.661157  0.690083  0.714876  0.706612     0.0  
4    0.524793  0.537190  0.487603  0.190083  0.144628  0.152893     0.0  
..        ...       ...       ...       ...       ...       ...     ...  
315  0.099174  0.181818  0.243802  0.247934  0.161157  0.157025    39.0  
316  0.285124  0.338843  0.404959  0.458678  0.487603  0.512397    39.0  
317  0.161157  0.161157  0.173554  0.157025  0.177686  0.148760    39.0  
318  0.409091  0.479339  0.524793  0.545455  0.574380  0.590909    39.0  
319  0.301653  0.293388  0.322314  0.322314  0.359504  0.355372    39.0  

[320 rows x 4096 columns]

In [54]:
test_data_set

0         1         2         3         4         5         6  \
0   0.309917  0.367769  0.417355  0.442149  0.528926  0.607438  0.657025   
1   0.454545  0.471074  0.512397  0.557851  0.595041  0.640496  0.681818   
2   0.541322  0.586777  0.640496  0.661157  0.685950  0.685950  0.690083   
3   0.644628  0.690083  0.702479  0.702479  0.706612  0.719008  0.727273   
4   0.578512  0.603306  0.632231  0.665289  0.677686  0.710744  0.723140   
..       ...       ...       ...       ...       ...       ...       ...   
75  0.144628  0.219008  0.326446  0.471074  0.570248  0.644628  0.677686   
76  0.252066  0.219008  0.227273  0.272727  0.318182  0.388430  0.458678   
77  0.355372  0.392562  0.446281  0.462810  0.475207  0.491736  0.500000   
78  0.545455  0.611570  0.640496  0.657025  0.636364  0.648760  0.690083   
79  0.334711  0.404959  0.475207  0.537190  0.561983  0.553719  0.586777   

           7         8         9  ...      4086      4087      4088      4089  \
0   0.677686  0.690083  0.685950  ...  0.665289  0.669422  0.652893  0.661157   
1   0.702479  0.710744  0.702479  ...  0.136364  0.157025  0.136364  0.148760   
2   0.698347  0.694215  0.690083  ...  0.483471  0.483471  0.495868  0.512397   
3   0.739669  0.719008  0.719008  ...  0.495868  0.495868  0.297521  0.074380   
4   0.739669  0.739669  0.743802  ...  0.157025  0.177686  0.194215  0.198347   
..       ...       ...       ...  ...       ...       ...       ...       ...   
75  0.710744  0.739669  0.760331  ...  0.367769  0.388430  0.165289  0.198347   
76  0.504132  0.516529  0.524793  ...  0.260331  0.260331  0.276859  0.293388   
77  0.504132  0.520661  0.545455  ...  0.190083  0.132231  0.111570  0.140496   
78  0.669422  0.665289  0.710744  ...  0.157025  0.169422  0.173554  0.148760   
79  0.623967  0.669422  0.690083  ...  0.561983  0.537190  0.512397  0.466942   

        4090      4091      4092      4093      4094  target  
0   0.475207  0.132231  0.148760  0.152893  0.161157     0.0  
1   0.152893  0.152893  0.152893  0.152893  0.152893     0.0  
2   0.528926  0.363636  0.111570  0.095041  0.111570     1.0  
3   0.099174  0.111570  0.115702  0.111570  0.107438     1.0  
4   0.206612  0.194215  0.165289  0.177686  0.161157     2.0  
..       ...       ...       ...       ...       ...     ...  
75  0.243802  0.219008  0.392562  0.309917  0.210744    37.0  
76  0.206612  0.128099  0.136364  0.157025  0.157025    38.0  
77  0.165289  0.169422  0.173554  0.173554  0.181818    38.0  
78  0.169422  0.165289  0.157025  0.173554  0.173554    39.0  
79  0.384298  0.363636  0.380165  0.384298  0.376033    39.0  

[80 rows x 4096 columns]

In [139]:
train_data_set = np.transpose(train_data_set)
test_data_set = np.transpose(test_data_set)

X_train = train_data_set
y_train = []

for i in range(40):
    for j in range(int(len(train_data_set)/ 40)):
        y_train.append(str(i))
        

In [140]:
X_test = test_data_set
y_test = []

for i in range(40):
    for j in range(int(len(test_data_set)/ 40)):
        y_test.append(str(i))
        

In [126]:
gnb = GaussianNB()

gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)

overall_accuracy = metrics.accuracy_score(y_test, y_pred)

In [127]:
print("Bayes Classifier with dimension = " + str(d))
print("\nOverall Accuracy = " + str(overall_accuracy))


Bayes Classifier with dimension = 4096

Overall Accuracy = 1.0


## Bayes Classifier with dimesion = 111

In [135]:
X_train_reduced_dimension = train_data_set_transformed
y_train_reduced_dimension = []

for i in range(40):
    for j in range(int(len(train_data_set_transformed)/ 40)):
        y_train_reduced_dimension.append(str(i))

X_train_reduced_dimension

array([[-8.29290331e+00,  3.02285622e+01,  2.41543149e+01, ...,
        -8.73786293e-01, -5.66741831e-02,  4.04960725e-02],
       [-7.64557547e+00,  3.51417325e+01,  1.22750050e+01, ...,
        -4.65948071e-01,  1.30449372e-01,  4.67527665e-01],
       [-8.11817755e+00,  2.82085837e+01,  2.50852021e+01, ...,
        -7.88608451e-01, -1.19643270e-01,  2.59223977e-01],
       ...,
       [ 3.13947253e+01,  3.04409600e+01,  2.56418657e+01, ...,
        -3.19052588e-01, -6.48079946e-02,  3.55924352e-01],
       [ 3.02008171e+01,  4.09947952e+01,  2.00702084e+01, ...,
        -4.68537219e-01, -6.65559262e-02,  6.07810380e-01],
       [ 3.08571030e+01,  3.49733539e+01,  2.34102081e+01, ...,
        -5.84183796e-01, -2.10560625e-01, -7.79441569e-02]])

In [136]:
X_train_reduced_dimension.shape

(320, 111)

In [137]:
X_test_reduced_dimension = test_data_set_transformed
y_test_reduced_dimension = []

for i in range(40):
    for j in range(int(len(test_data_set_transformed)/ 40)):
        y_test_reduced_dimension.append(str(i))
        
X_test_reduced_dimension

array([[-8.44927168e+00,  3.16692396e+01,  2.39182316e+01, ...,
        -3.32461002e-01,  7.65168901e-02,  1.27667589e-01],
       [-7.64817839e+00,  2.41778890e+01,  2.68682159e+01, ...,
        -6.99703674e-01, -4.19659079e-01,  3.49745287e-01],
       [-6.38846022e+00,  2.70653310e+01,  2.20660192e+01, ...,
        -7.52367705e-01, -4.21027474e-02,  4.75540818e-02],
       ...,
       [ 3.20582337e+01,  2.32533442e+01,  2.17620683e+01, ...,
        -4.36503361e-01, -9.39702391e-02,  7.04456699e-01],
       [ 3.11863400e+01,  3.09539340e+01,  2.59429320e+01, ...,
        -5.11462215e-01,  3.35048702e-02,  1.73611141e-01],
       [ 3.03147586e+01,  3.74984528e+01,  2.45753793e+01, ...,
        -4.34260533e-01, -3.09021547e-01,  5.99813400e-01]])

In [138]:
X_test_reduced_dimension.shape

(80, 111)

In [132]:
gnb_reduced_dimension = GaussianNB()

gnb_reduced_dimension.fit(X_train_reduced_dimension, y_train_reduced_dimension)

y_pred_reduced_dimension = gnb_reduced_dimension.predict(X_test_reduced_dimension)

overall_accuracy_reduced_dimension = metrics.accuracy_score(y_test_reduced_dimension, y_pred_reduced_dimension)

print("Bayes Classifier with dimension = " + str(d_prime))
print("\nOverall Accuracy = " + str(overall_accuracy_reduced_dimension))

Bayes Classifier with dimension = 111

Overall Accuracy = 1.0
