<a href="https://colab.research.google.com/github/Rit-ctrl/Pattern-Recognition_2021/blob/main/Assignment_1/Assignment-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Q1. Calculate the distance between the two normalized histograms H1 and H2 using each of the
following methods:

I. KL Distance

II. Bhattacharyya Distance

H1 = [ 0.24, 0.2, 0.16, 0.12, 0.08, 0.04, 0.12, 0.04]

H2 = [ 0.22, 0.23, 0.16, 0.13, 0.11, 0.08, 0.05, 0.02]

#### KL Distance -

In [2]:
import numpy as np

def kl(p, q):
    p = np.asarray(p, dtype=np.float)
    q = np.asarray(q, dtype=np.float)

    return np.sum(np.where(p != 0, p * np.log(p / q), 0))

In [3]:
p = [ 0.24, 0.2, 0.16, 0.12, 0.08, 0.04, 0.12, 0.04]

q = [ 0.22, 0.23, 0.16, 0.13, 0.11, 0.08, 0.05, 0.02]

kl(p,q)

0.06290516707464022

In [5]:
#verification
from scipy import special

np.sum(scipy.special.rel_entr(p,q))


0.06290516707464022

#### Bhattacharyya Distance

In [8]:
from math import sqrt
coeff = []

def bhattacharya(p,q):
    p = np.asarray(p, dtype=np.float)
    q = np.asarray(q, dtype=np.float)

    for i in range(0,len(p)):
        coeff.append(sqrt(p[i]*q[i]))
    
    coeff_np = np.array(coeff)
    return -1*np.log(np.sum(coeff_np))



In [9]:
bhattacharya(p,q)

0.014830056106628986

In [15]:
#verification

!pip install dictances
import dictances
a = {
    "event_1": 0.24,
    "event_2": 0.2,
    "event_3": 0.16,
    "event_4": 0.12,
    "event_5": 0.08,
    "event_6": 0.04,
    "event_7": 0.12,
    "event_8": 0.04,
}
b = {
    "event_1": 0.22,
    "event_2": 0.23,
    "event_3": 0.16,
    "event_4": 0.13,
    "event_5": 0.11,
    "event_6": 0.08,
    "event_7": 0.05,
    "event_8": 0.02,
}

dictances.bhattacharyya(a,b)

0.014830056106628874

### Q2. Given (hq-ht)​ T​ ​ = (0.5 0.5 -0.5 -0.25 -0.25) and 

A = [ 

[1,0.135,0.195,0.137,0.157],

[0.135,1,0.2,0.309,0.143],

[0.195,0.2,1,0.157,0.122],

[0.137,0.309,0.157,1,0.195],

[0.157,0.143,0.122,0.195,1] 

]

Find the quadratic form distance.

In [33]:
import numpy as np

In [34]:
hq_ht_T = np.array([0.5, 0.5, -0.5, -0.25, -0.25])
A = np.array([[1,0.135,0.195,0.137,0.157],[0.135,1,0.2,0.309,0.143],[0.195,0.2,1,0.157,0.122],[0.137,0.309,0.157,1,0.195],[0.157,0.143,0.122,0.195,1]])
hq_ht = hq_ht_T[...,None]

In [35]:
print(hq_ht,"\n\n",hq_ht_T,"\n\n",A)

[[ 0.5 ]
 [ 0.5 ]
 [-0.5 ]
 [-0.25]
 [-0.25]] 

 [ 0.5   0.5  -0.5  -0.25 -0.25] 

 [[1.    0.135 0.195 0.137 0.157]
 [0.135 1.    0.2   0.309 0.143]
 [0.195 0.2   1.    0.157 0.122]
 [0.137 0.309 0.157 1.    0.195]
 [0.157 0.143 0.122 0.195 1.   ]]


In [36]:
x = hq_ht_T.dot(A)
quadratic_form_distance = x.dot(hq_ht)
print(quadratic_form_distance)

[0.652625]


In [37]:
#easier way
hq_ht_T @ A @ hq_ht

array([0.652625])

### Q3. Compare two text files doc1.txt and doc2.txt using cosine distance.

doc1.txt

MATLAB is a program for solving engineering and mathematical problems. The basic
MATLAB objects are vectors and matrices, so you must be familiar with these before making extensive use of this program.

doc2.txt

MATLAB works with essentially one kind of object, a rectangular numerical matrix. Here is
some basic information on using MATLAB matrix commands.

In [38]:
doc1="MATLAB is a program for solving engineering and mathematical problems. The basic MATLAB objects are vectors and matrices, so you must be familiar with these before making extensive use of this program."

In [39]:
doc2="MATLAB works with essentially one kind of object, a rectangular numerical matrix. Here is some basic information on using MATLAB matrix commands."

In [78]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

count_vectorizer=CountVectorizer(stop_words='english')

documents=[doc1,doc2]

sparse_matrix=count_vectorizer.fit_transform(documents)

In [79]:
doc_term_matrix = sparse_matrix.todense() ## to dense allocates memory even for missing values (sparse doesnt)
df = pd.DataFrame(doc_term_matrix, 
                  columns=count_vectorizer.get_feature_names(), 
                  index=['doc1', 'doc2'])
df

basic  commands  engineering  essentially  ...  use  using  vectors  works
doc1      1         0            1            0  ...    1      0        1      0
doc2      1         1            0            1  ...    0      1        0      1

[2 rows x 24 columns]

In [108]:
d1_dot_d2=np.dot(np.asarray(doc_term_matrix)[0],np.asarray(doc_term_matrix)[1])
d1_norm=np.linalg.norm(np.asarray(doc_term_matrix)[0])
d2_norm=np.linalg.norm(np.asarray(doc_term_matrix)[1])
cosine_sim=d1_dot_d2/(d1_norm * d2_norm)

print(f"Cosine similarity : {cosine_sim}, Cosine distance : {1-cosine_sim}")

Cosine similarity : 0.26352313834736496, Cosine distance : 0.736476861652635


In [115]:
#verification
from sklearn.metrics.pairwise import cosine_similarity
q3_res=cosine_similarity(doc_term_matrix[0],doc_term_matrix[1])

print(f"Cosine similarity :{q3_res[0][0]} , cosine distance :{1-q3_res[0][0]}")

Cosine similarity :0.26352313834736496 , cosine distance :0.736476861652635


### Q4. Classify flower 0, 50, and 100 from the Iris Dataset (.csv file) attached along with the assignment document into one of the three classes as given in dataset specification:

- Dataset Specifications:

  Total number of samples = 150
  Number of classes = 3 (Iris setosa, Iris virginica, and Iris versicolor)
  The number of samples in each class = 50.
  

- Directions to classify:

  1. Use features PetalLengthCm and PetalWidthCm only for classification.
  2. Consider flowers 0,50 and 100 as test cases.
  3. Plot the distribution of rest 147 sample points along with their classes( differentiate
  classes with different colour). Consider PetalWidthCm along Y-axis and PetalLengthCm
  along X-axis.
  4. Capture the properties of the distribution and use suitable distance metrics to classify the
  flowers 0,50 and 100 into one of the classes.
  5. Print their class and plot the points on the previous plot with a marker differentiating the
  three points. 

### Q5. Consider the following images. Obtain the histograms for each of the images. Using a suitable distance measure, find the distance between the query image and reference images.

In [119]:
import matplotlib.pyplot as plt



HTTPError: ignored